### ISSUE TITLE
如何运行？

### ISSUE THREAD

**Issue by wxtech** [chengdedeng/waf#8]
waf console 报错 java.lang.ClassNotFoundException: javax.servlet.Filter 请指教如何运行 谢谢！

**Comment by chengdedeng** [comment]
javax.servlet.Filter这个类是属于嵌入式Tomcat提供的一个类，不应该没有该类，你能说下你是如何运行的吗？

**Comment by chengdedeng** [comment]
@wxtech 我们可以在gitter中聊，我好给你提供更多的帮助。

**Comment by wxtech** [comment]
git clone https://github.com/chengdedeng/waf.git

**Comment by wxtech** [comment]
不好意思 不用gitter

操作步骤如下：
git clone https://github.com/chengdedeng/waf.git
cd waf
mvn package
cd target/jsw/waf/bin
waf console
报错 java.lang.ClassNotFoundException: javax.servlet.Filter 请指教如何运行 谢谢！

**Comment by chengdedeng** [comment]
解压waf-3.0.0-SNAPSHOT-release.zip，然后去它里面运行

**Comment by chengdedeng** [comment]
sorry，解压waf-*-release.zip

**Comment by wxtech** [comment]
谢谢！ 如果能详细写一下如何能运行起来就好了。。。还是报错。。。哪里需要什么配置吗？

**Comment by wxtech** [comment]
jvm 1    | 20:48:58.127 default [WrapperSimpleAppMain-EventThread] INFO  o.a.c.f.state.ConnectionStateManager - State change: CONNECTED
jvm 1    | 20:48:58.128 default [Curator-ConnectionStateManager-0] INFO  i.y.waf.service.ZkClusterService - zookeeper state:CONNECTED
jvm 1    | 20:48:58.203 default [WrapperSimpleAppMain-SendThread(139.224.227.113:2181)] INFO  org.apache.zookeeper.ClientCnxn - Unable to read additional data from server sessionid 0x265fa3a729d0001, likely server has closed socket, closing socket connection and attempting reconnect
jvm 1    |
jvm 1    | WrapperSimpleApp: Encountered an error running main: java.util.ServiceConfigurationError: info.yangguo.waf.service.ClusterService: Provider info.yangguo.waf.service.ZkClusterService could not be instantiated
jvm 1    | java.util.ServiceConfigurationError: info.yangguo.waf.service.ClusterService: Provider info.yangguo.waf.service.ZkClusterService could not be instantiated
jvm 1    |      at java.util.ServiceLoader.fail(ServiceLoader.java:232)
jvm 1    |      at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
jvm 1    |      at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
jvm 1    |      at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
jvm 1    |      at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
jvm 1    |      at info.yangguo.waf.Application.main(Application.java:56)
jvm 1    |      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jvm 1    |      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jvm 1    |      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jvm 1    |      at java.lang.reflect.Method.invoke(Method.java:498)
jvm 1    |      at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
jvm 1    |      at java.lang.Thread.run(Thread.java:748)
jvm 1    | Caused by: java.lang.RuntimeException: org.apache.zookeeper.KeeperException$UnimplementedException: KeeperErrorCode = Unimplemented for /waf/config/security/info.yangguo.waf.request.security.ArgsSecurity
jvm 1    |      at info.yangguo.waf.service.ZkClusterService.initFilter(ZkClusterService.java:647)
jvm 1    |      at info.yangguo.waf.service.ZkClusterService.lambda$new$2(ZkClusterService.java:95)
jvm 1    |      at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
jvm 1    |      at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
jvm 1    |      at info.yangguo.waf.service.ZkClusterService.<init>(ZkClusterService.java:94)
jvm 1    |      at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
jvm 1    |      at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
jvm 1    |      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
jvm 1    |      at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
jvm 1    |      at java.lang.Class.newInstance(Class.java:442)
jvm 1    |      at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
jvm 1    |      ... 9 more
jvm 1    | Caused by: org.apache.zookeeper.KeeperException$UnimplementedException: KeeperErrorCode = Unimplemented for /waf/config/security/info.yangguo.waf.request.security.ArgsSecurity
jvm 1    |      at org.apache.zookeeper.KeeperException.create(KeeperException.java:103)
jvm 1    |      at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
jvm 1    |      at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1525)
jvm 1    |      at org.apache.curator.framework.imps.CreateBuilderImpl$17.call(CreateBuilderImpl.java:1181)
jvm 1    |      at org.apache.curator.framework.imps.CreateBuilderImpl$17.call(CreateBuilderImpl.java:1158)
jvm 1    |      at org.apache.curator.connection.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:64)
jvm 1    |      at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:100)
jvm 1    |      at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:1155)
jvm 1    |      at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:605)
jvm 1    |      at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:595)
jvm 1    |      at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:49)
jvm 1    |      at info.yangguo.waf.service.ZkClusterService.initFilter(ZkClusterService.java:643)
jvm 1    |      ... 19 more
jvm 1    | 20:48:58.304 default [WrapperSimpleAppMain-EventThread] INFO  o.a.c.f.state.ConnectionStateManager - State change: SUSPENDED
jvm 1    | 20:48:58.304 default [Curator-ConnectionStateManager-0] INFO  i.y.waf.service.ZkClusterService - zookeeper state:SUSPENDED

**Comment by wxtech** [comment]
jvm 1    | 20:48:58.127 default [WrapperSimpleAppMain-EventThread] INFO  o.a.c.f.state.ConnectionStateManager - State change: CONNECTED
jvm 1    | 20:48:58.128 default [Curator-ConnectionStateManager-0] INFO  i.y.waf.service.ZkClusterService - zookeeper state:CONNECTED
jvm 1    | 20:48:58.203 default [WrapperSimpleAppMain-SendThread(127.0.0.1:2181)] INFO  org.apache.zookeeper.ClientCnxn - Unable to read additional data from server sessionid 0x265fa3a729d0001, likely server has closed socket, closing socket connection and attempting reconnect
jvm 1    |
jvm 1    | WrapperSimpleApp: Encountered an error running main: java.util.ServiceConfigurationError: info.yangguo.waf.service.ClusterService: Provider info.yangguo.waf.service.ZkClusterService could not be instantiated
jvm 1    | java.util.ServiceConfigurationError: info.yangguo.waf.service.ClusterService: Provider info.yangguo.waf.service.ZkClusterService could not be instantiated
jvm 1    |      at java.util.ServiceLoader.fail(ServiceLoader.java:232)
jvm 1    |      at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
jvm 1    |      at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
jvm 1    |      at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
jvm 1    |      at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
jvm 1    |      at info.yangguo.waf.Application.main(Application.java:56)
jvm 1    |      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jvm 1    |      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jvm 1    |      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jvm 1    |      at java.lang.reflect.Method.invoke(Method.java:498)
jvm 1    |      at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
jvm 1    |      at java.lang.Thread.run(Thread.java:748)
jvm 1    | Caused by: java.lang.RuntimeException: org.apache.zookeeper.KeeperException$UnimplementedException: KeeperErrorCode = Unimplemented for /waf/config/security/info.yangguo.waf.request.security.ArgsSecurity
jvm 1    |      at info.yangguo.waf.service.ZkClusterService.initFilter(ZkClusterService.java:647)
jvm 1    |      at info.yangguo.waf.service.ZkClusterService.lambda$new$2(ZkClusterService.java:95)
jvm 1    |      at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
jvm 1    |      at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
jvm 1    |      at info.yangguo.waf.service.ZkClusterService.<init>(ZkClusterService.java:94)
jvm 1    |      at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
jvm 1    |      at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
jvm 1    |      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
jvm 1    |      at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
jvm 1    |      at java.lang.Class.newInstance(Class.java:442)
jvm 1    |      at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
jvm 1    |      ... 9 more
jvm 1    | Caused by: org.apache.zookeeper.KeeperException$UnimplementedException: KeeperErrorCode = Unimplemented for /waf/config/security/info.yangguo.waf.request.security.ArgsSecurity
jvm 1    |      at org.apache.zookeeper.KeeperException.create(KeeperException.java:103)
jvm 1    |      at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
jvm 1    |      at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1525)
jvm 1    |      at org.apache.curator.framework.imps.CreateBuilderImpl$17.call(CreateBuilderImpl.java:1181)
jvm 1    |      at org.apache.curator.framework.imps.CreateBuilderImpl$17.call(CreateBuilderImpl.java:1158)
jvm 1    |      at org.apache.curator.connection.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:64)
jvm 1    |      at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:100)
jvm 1    |      at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:1155)
jvm 1    |      at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:605)
jvm 1    |      at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:595)
jvm 1    |      at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:49)
jvm 1    |      at info.yangguo.waf.service.ZkClusterService.initFilter(ZkClusterService.java:643)
jvm 1    |      ... 19 more
jvm 1    | 20:48:58.304 default [WrapperSimpleAppMain-EventThread] INFO  o.a.c.f.state.ConnectionStateManager - State change: SUSPENDED
jvm 1    | 20:48:58.304 default [Curator-ConnectionStateManager-0] INFO  i.y.waf.service.ZkClusterService - zookeeper state:SUSPENDED

**Comment by chengdedeng** [comment]
这错误一看就是你zookeeper没有启动或者配置啊

**Comment by wxtech** [comment]
zookeeper 版本不一致导致 改用 zookeeper-3.5.3-beta 后成功启动了，感谢！
